### PR TITLE
Update to support Puppet 6, fix issue with Helix 2019.1, bundle RPM key

### PR DESCRIPTION
**Pull request by runejuhl**
This PR 

+ allows the module to work under Puppet 6
+ fixes an issue with the service daemon path under Helix 2019.1
+ bundles the RPM GPG key and adds a parameter for using an URL instead
+ ensures the license file is removed if the parameter is `undef`
+ updates the usage examples to avoid dependency arrows (as per the Puppet style guide)

### CODE REVIEW

**Comment by runejuhl** [comment]
@mmarseglia, please let me know if you'd like me to make any changes to this PR before merge.

**Comment by mmarseglia** [comment]
Hi, thank you for this PR.  I'm sorry for the delay.  It appears I had some comments a few months ago but they didn't get published.  I will review today.  Thank you for your patience.

**Review by mmarseglia — COMMENTED** [review]
I think we need to add a note in the readme about which versions of Perforce the module supports. The perforce version type has a regex that won't support older versions.

What happens if someone has perforce managed by this module and then upgrades the module?

I really like all these changes, this is great.  Thank you so much for sharing these.

**Comment by runejuhl** [comment]
> Hi, thank you for this PR. I'm sorry for the delay. It appears I had some comments a few months ago but they didn't get published. I will review today. Thank you for your patience.

No worries!

> I think we need to add a note in the readme about which versions of Perforce the module supports. The perforce version type has a regex that won't support older versions.

I'd be fine with adding a regex that can match older versions as well. Do you have any idea of which Perforce release that introduced the current version string format? 

> What happens if someone has perforce managed by this module and then upgrades the module?

Hopefully they'd have set version to something other than `"latest"`, in which case it wouldn't do anything.

I haven't tried upgrading the Perforce install I've managing with this module, yet, but it's probably something that I'll need to do in the not too distant future...
 
> I really like all these changes, this is great. Thank you so much for sharing these.

You're very welcome -- and same to you, thank you for making this module public. ...and if you're ever in a situation where you no longer have the need for Perforce/time for maintaining/have taken up goat farming instead please consider handing the module over to @voxpupuli :slightly_smiling_face:

**Comment by mmarseglia** [comment]
I don't recall what the version string was.  Let's just merge this in and maybe do it later.

**Pull request merged**
